/* lumiwords.h — Lumi 의 '아는 낱말' 표 (한 곳에서만 적습니다)
 * ==========================================================
 * 문법 낱말 · 자료형 · 형변환 · 내장 함수의 이름과 짧은 도움말입니다.
 *
 * 이 표를 쓰는 곳이 둘입니다:
 *   1) lsp.c          — 편집기 자동완성과 마우스 올렸을 때 설명
 *   2) ide-cpp .../lumitokenizer.cpp — Lumina IDE 의 색칠과 자동완성
 * 그래서 헤더 하나에 담아 양쪽이 그대로 include 합니다.
 * **새 내장 함수를 만들면 여기에도 반드시 한 줄 넣으세요.**
 *
 * hint 의 [ ] 는 생략할 수 있는 자리라는 뜻입니다.
 */
#ifndef LUMI_WORDS_H
#define LUMI_WORDS_H

typedef enum {
    LW_KEYWORD,   /* 문법 낱말 (val, if, class ...) */
    LW_TYPE,      /* 선언에 쓰는 자료형 (int x = 1) */
    LW_CAST,      /* 형변환 함수 (int("42")) — 자료형 이름도 부르면 이쪽 */
    LW_FUNC       /* 내장 함수 (print, len, split ...) */
} LumiWordKind;

typedef struct {
    const char  *name;
    LumiWordKind kind;
    const char  *hint;
} LumiWordDef;

static const LumiWordDef LUMI_WORDS[] = {
    /* 문법 낱말 (lexer.c KEYWORDS) */
    {"val",      LW_KEYWORD, "name = value"},
    {"global",   LW_KEYWORD, "name = value"},
    {"local",    LW_KEYWORD, "name = value"},
    {"if",       LW_KEYWORD, "cond:"},
    {"elif",     LW_KEYWORD, "cond:"},
    {"else",     LW_KEYWORD, ":"},
    {"while",    LW_KEYWORD, "cond:"},
    {"for",      LW_KEYWORD, "x in seq:   /   i = 0, cond, step:"},
    {"switch",   LW_KEYWORD, "value:"},
    {"case",     LW_KEYWORD, "value:"},
    {"default",  LW_KEYWORD, ":"},
    {"func",     LW_KEYWORD, "name(params):"},
    {"return",   LW_KEYWORD, "value"},
    {"class",    LW_KEYWORD, "Name:   /   Name from Base:"},
    {"from",     LW_KEYWORD, "Base:   (class Name from Base:)"},
    {"bring",    LW_KEYWORD, "library   /   library up name"},
    {"up",       LW_KEYWORD, "name   (bring library up name)"},
    {"break",    LW_KEYWORD, ""},
    {"continue", LW_KEYWORD, ""},
    {"in",       LW_KEYWORD, "value in seq"},
    {"and",      LW_KEYWORD, ""},
    {"or",       LW_KEYWORD, ""},
    {"not",      LW_KEYWORD, ""},
    {"true",     LW_KEYWORD, ""},
    {"false",    LW_KEYWORD, ""},
    {"use",      LW_KEYWORD, "f = open(read, \"note.txt\"):   closes it for you"},
    {"this",     LW_KEYWORD, ""},
    {"super",    LW_KEYWORD, ""},
    {"abstract", LW_KEYWORD, "func name():   declares an abstract method"},
    {"try",      LW_KEYWORD, ":   attempts block execution"},
    {"catch",    LW_KEYWORD, "[Type] [e]:   catches errors"},
    {"safe",     LW_KEYWORD, ":   runs when no error occurred"},
    {"always",   LW_KEYWORD, ":   always runs at the end"},
    {"error",    LW_KEYWORD, "(\"msg\")   /   (Type, \"msg\")   raises an error"},
    {"test",     LW_KEYWORD, "\"name\":   a test block, run by  lumi test"},
    /* 선언에 쓰는 자료형 (lexer.c TYPE_NAMES) */
    {"int",   LW_TYPE, "name = value   (whole number)"},
    {"float", LW_TYPE, "name = value   (real number)"},
    {"num",   LW_TYPE, "name = value   (int or float)"},
    {"char",  LW_TYPE, "name = value   (one letter)"},
    {"str",   LW_TYPE, "name = value   (text)"},
    {"text",  LW_TYPE, "name = value   (text)"},
    {"seq",   LW_TYPE, "name = value   (list/tuple/text)"},
    {"bytes", LW_TYPE, "name = value   (bytes)"},
    {"bool",  LW_TYPE, "name = value   (true/false)"},
    {"list",  LW_TYPE, "name = value   (list)"},
    {"tuple", LW_TYPE, "name = value   (tuple)"},
    {"dict",  LW_TYPE, "name = value   (dict)"},
    /* 같은 이름을 부르면 형변환 함수가 된다 */
    {"int",   LW_CAST, "(value)   3.9 -> 3, \"A\" -> 65"},
    {"float", LW_CAST, "(value)   7 -> 7.0"},
    {"num",   LW_CAST, "(value)   \"0xff\" -> 255"},
    {"char",  LW_CAST, "(value)   65 -> \"A\""},
    {"str",   LW_CAST, "(value)"},
    {"text",  LW_CAST, "(value)   same as str"},
    {"seq",   LW_CAST, "(value)"},
    {"bytes", LW_CAST, "(int list)   text -> use encode"},
    {"bool",  LW_CAST, "(value)"},
    {"list",  LW_CAST, "(value)"},
    {"tuple", LW_CAST, "(value)"},
    {"dict",  LW_CAST, "([key, value] list)"},
    /* 내장 함수 (builtins.inc) */
    {"print",    LW_FUNC, "(value, ... [, keep(ending)])"},
    {"keep",     LW_FUNC, "([ending])   print only: no newline"},
    {"input",    LW_FUNC, "([prompt])"},
    {"start",    LW_FUNC, "(function, value, ...)   run a task"},
    {"wait",     LW_FUNC, "(task)   wait for a task and get its result"},
    {"type",     LW_FUNC, "(value)"},
    {"len",      LW_FUNC, "(seq, dict, or open file -> bytes)"},
    {"isa",      LW_FUNC, "(value, Class)"},
    {"forr",     LW_FUNC, "(val i = 0, cond, step)"},
    {"bin",      LW_FUNC, "(int)   11 -> \"0b1011\""},
    {"hex",      LW_FUNC, "(int)   255 -> \"0xff\""},
    {"isalpha",  LW_FUNC, "(text)   all letters?"},
    {"isdigit",  LW_FUNC, "(text)   all digits?"},
    {"isalgit",  LW_FUNC, "(text)   all letters or digits?"},
    {"hasalpha", LW_FUNC, "(text)   any letter?"},
    {"hasdigit", LW_FUNC, "(text)   any digit?"},
    {"hasalgit", LW_FUNC, "(text)   any letter or digit?"},
    {"incount",  LW_FUNC, "(what, seq)   how many"},
    {"infind",   LW_FUNC, "(what, seq)   list of places"},
    {"inpair",   LW_FUNC, "([shape,] seq or dict)   shape: list / tuple / dict"},
    {"upper",    LW_FUNC, "([where,] text)   where: place / a:b / [a,b]"},
    {"lower",    LW_FUNC, "([where,] text)   where: place / a:b / [a,b]"},
    {"strip",    LW_FUNC, "([where,] text)   removes spaces"},
    {"split",    LW_FUNC, "([sep,] text)   -> list"},
    {"join",     LW_FUNC, "([glue,] seq)   -> text"},
    {"replace",  LW_FUNC, "(old, new, text)"},
    {"format",   LW_FUNC, "([val1, val2, ... | list | dict,] text) -> text"},
    {"sort",     LW_FUNC, "([up,] seq)   up: true / false"},
    {"insor",    LW_FUNC, "([up,] place, seq)   sort by inner place"},
    {"shuffle",  LW_FUNC, "(seq)"},
    {"each",     LW_FUNC, "(func, seq)   call func on every item -> list"},
    {"encode",   LW_FUNC, "([encoding,] text) -> bytes"},
    {"decode",   LW_FUNC, "([encoding,] bytes) -> text"},
    {"push",     LW_FUNC, "(list, value) -> new length"},
    {"pop",      LW_FUNC, "(list) -> last value"},
    {"insert",   LW_FUNC, "(place, value, list) -> new length"},
    {"erase",    LW_FUNC, "([where,] list) -> how many removed"},
    {"keys",     LW_FUNC, "(dict) -> list"},
    {"values",   LW_FUNC, "(dict) -> list"},
    {"has",      LW_FUNC, "(dict, key) -> true / false"},
    {"del",      LW_FUNC, "(dict[, key]) -> how many removed"},
    {"eval",     LW_FUNC, "(text)   runs an expression written as text"},
    {"read",     LW_FUNC, "([encoding,] file) -> text"},
    {"write",    LW_FUNC, "([encoding,] text, file) -> how many characters"},
    {"append",   LW_FUNC, "([encoding,] text, file)   adds to the end"},
    {"isfile",   LW_FUNC, "(file) -> true / false"},
    {"newfile",  LW_FUNC, "(file)   makes an empty file if it is not there"},
    {"newdir",   LW_FUNC, "(folder)   makes an empty folder if it is not there"},
    {"delfile",  LW_FUNC, "(file)   deletes the file"},
    {"deldir",   LW_FUNC, "(folder)   deletes the folder"},
    {"renamefile", LW_FUNC, "(new name, file)   renames the file"},
    {"movefile", LW_FUNC, "(folder, file)   moves the file into that folder"},
    {"open",     LW_FUNC, "([encoding,] [read/write/append,] file) -> open file"},
    {"readline", LW_FUNC, "(open file) -> next line, without the newline"},
    {"writeline", LW_FUNC, "([encoding,] text, file)   writes one line + newline"},
    {"isend",    LW_FUNC, "(open file)   nothing left to read?"},
    {"close",    LW_FUNC, "(open file)   closes it"},
    {"move",     LW_FUNC, "(place, open file)   go to that byte place"},
    {"where",    LW_FUNC, "(open file) -> the byte place it is at now"},
    {"time",     LW_FUNC, "() -> unix timestamp float"},
    {"now",      LW_FUNC, "([format]) -> current date-time text"},
    {"sleep",    LW_FUNC, "(seconds)   pause execution"},
    {"clock",    LW_FUNC, "() -> high-resolution monotonic timer float"},
    {"date",     LW_FUNC, "([timestamp]) -> date dict"},
    {"timeformat", LW_FUNC, "(format, [timestamp]) -> text"},
    {"timeparse", LW_FUNC, "(text, format) -> timestamp float"},
    {"timezone", LW_FUNC, "() -> timezone dict"},
    {"dateadd",  LW_FUNC, "(timestamp, amount, unit) -> timestamp float"},
    {"datediff", LW_FUNC, "(t1, t2, unit) -> difference float"},
    {"isleap",   LW_FUNC, "(year or timestamp) -> true / false"},
    {"timed",    LW_FUNC, "(func, [args...]) -> [result, elapsed seconds]"},
    {"uptime",   LW_FUNC, "() -> elapsed interpreter uptime float"},
    {"runtime",  LW_FUNC, "() -> elapsed interpreter uptime float"},
    {"rand",     LW_FUNC, "([a, b]) -> random float / int / element"},
    {"filter",   LW_FUNC, "(func, sequence) -> filtered sequence"},
    {"sum",      LW_FUNC, "(sequence) -> total sum number"},
    {"clamp",    LW_FUNC, "(val, min, max) -> bounded number"},
    {"env",      LW_FUNC, "(name) -> environment variable text"},
    {"getenv",   LW_FUNC, "(name) -> environment variable text"},
    {"args",     LW_FUNC, "([place]) -> command line arguments list / one argument"},
    {"assert",   LW_FUNC, "(condition[, note]) -> fails the test when not true"},
    {"assertsame", LW_FUNC, "(expected, actual) -> fails the test and shows both"},
    {"listdir",  LW_FUNC, "([file|dir,] folder) -> names inside the folder"},
    {"filename", LW_FUNC, "(path) -> the last piece"},
    {"foldername", LW_FUNC, "(path) -> the folder part"},
    {"pathjoin", LW_FUNC, "(pieces...) -> joined with this OS separator"},
    {"fullpath", LW_FUNC, "(path) -> absolute path"},
    {"sha256",   LW_FUNC, "(text or bytes) -> 64 hex letters"},
    {"md5",      LW_FUNC, "(text or bytes) -> 32 hex letters (old files only)"},
    {"base64",   LW_FUNC, "(text or bytes) -> base64 text"},
    {"unbase64", LW_FUNC, "(text) -> bytes"},
    {"ismatch",  LW_FUNC, "(pattern, text) -> whole text matches?"},
    {"hasmatch", LW_FUNC, "(pattern, text) -> found anywhere?"},
    {"findmatch", LW_FUNC, "(pattern, text) -> first match, or none"},
    {"findmatches", LW_FUNC, "(pattern, text) -> list of every match"},
    {"findgroups", LW_FUNC, "(pattern, text) -> the ( ) parts, or none"},
    {"replacematch", LW_FUNC, "(pattern, new, text) -> text with matches replaced"},
    {"splitmatch", LW_FUNC, "(pattern, text) -> list cut at each match"},
    {"shell",    LW_FUNC, "(command) -> what the program printed"},
    {"shellcode", LW_FUNC, "(command) -> exit code (0 = ok)"},
    {"httpserve", LW_FUNC, "(port, handler[, count])   low level - use http.serve"},
    /* 남의 C 라이브러리 불러 쓰기 — 위험합니다. 감싼 라이브러리를 쓰세요 (bring sqlite) */
    {"cload",    LW_FUNC, "(name) -> library handle    DANGEROUS - prefer a wrapper library"},
    {"cclose",   LW_FUNC, "(handle)                    close a loaded library"},
    {"chas",     LW_FUNC, "(handle, funcname) -> true / false"},
    {"ccall",    LW_FUNC, "(handle, funcname, signature, args) -> result   DANGEROUS"},
    {"cbuf",     LW_FUNC, "(nbytes) -> address         set aside zeroed memory"},
    {"cfree",    LW_FUNC, "(address)                   only for addresses from cbuf"},
    {"cget",     LW_FUNC, "(kind, address) -> value    kind: c h i l p f d"},
    {"cput",     LW_FUNC, "(value, kind, address)      write one value"},
    {"ctext",    LW_FUNC, "(address) -> text           read a UTF-8 string"},
    {"cbytes",   LW_FUNC, "(length, address) -> bytes"},
    {"add",      LW_FUNC, "(a, b) -> elementwise addition number or sequence"},
    {"sub",      LW_FUNC, "(a, b) -> elementwise subtraction number or sequence"},
    {"mul",      LW_FUNC, "(a, b) -> elementwise multiplication number or sequence"},
    {"div",      LW_FUNC, "(a, b) -> elementwise division number or sequence"},
    {"mod",      LW_FUNC, "(a, b) -> elementwise modulo number or sequence"},
    {"pow",      LW_FUNC, "(a, b) -> elementwise power number or sequence"},
    {"neg",      LW_FUNC, "(a) -> elementwise negation number or sequence"}
};

#define LUMI_WORD_COUNT (sizeof(LUMI_WORDS) / sizeof(LUMI_WORDS[0]))

#endif /* LUMI_WORDS_H */
